### ISSUE TITLE
能否增加其他的模型支持？

### ISSUE THREAD

**Issue by 223333** [maxoyed/koishi-plugin-qianfan-chat#1]
千帆好像有几个免费的模型可以用，
![image](https://github.com/maxoyed/koishi-plugin-qianfan-chat/assets/11299674/0ccdec7d-d7d3-44cd-8315-2d48496682eb)
还有几个价格比较便宜的，可否让查价支持手动填写模型名称嘞

**Comment by maxoyed** [comment]
模型名称和endpoint不一样，手动填写的话还需要填一下endpoint，这两天我空了把其他模型加上去
